In [2]:
#imports
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from nltk.sentiment.vader import SentimentIntensityAnalyzer
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
df = pd.read_csv('./outputs/sports-clean.csv', index_col='Unnamed: 0')
df

                                                        title subreddit
Unnamed: 0
0                                [Brett Kollmann] Damn, Mike.       nfl
1           [Highlight] Odell Beckham Jr with the rare but...       nfl
2           Breaking News: Antonio Brown Leaves The Bucs W...       nfl
3                         Beckham Jr with the rare butt punch       nfl
4             Tom Brady looking at AB during his antics today       nfl
...                                                       ...       ...
7491        2023 Reverse Retro Concept Series - Boston Bruins    hockey
7492                               Fun Fact about Boston Fans    hockey
7493        Tricky Ricky Rakell does it himself and scores...    hockey
7494        [BUF 3 - NYI 1] Tage Thompson hammers the one ...    hockey
7495        [PIT v DET] Matheson to Rakell who goes 5 hole...    hockey

[7496 rows x 2 columns]

In [8]:
sia = SentimentIntensityAnalyzer()
scores = [sia.polarity_scores(each) for each in df['title']]
score_df = pd.DataFrame(scores)
score_df

        neg    neu    pos  compound
0     0.474  0.526  0.000   -0.4019
1     0.000  1.000  0.000    0.0000
2     0.220  0.780  0.000   -0.4767
3     0.000  1.000  0.000    0.0000
4     0.000  1.000  0.000    0.0000
...     ...    ...    ...       ...
7491  0.000  1.000  0.000    0.0000
7492  0.000  0.548  0.452    0.5106
7493  0.167  0.833  0.000   -0.1531
7494  0.000  1.000  0.000    0.0000
7495  0.000  1.000  0.000    0.0000

[7496 rows x 4 columns]

In [9]:
df2 = pd.concat([df, score_df], axis=1)
df2

,title,subreddit,neg,neu,pos,compound
0,"[Brett Kollmann] Damn, Mike.",nfl,0.474,0.526,0.000,-0.4019
1,[Highlight] Odell Beckham Jr with the rare but...,nfl,0.000,1.000,0.000,0.0000
2,Breaking News: Antonio Brown Leaves The Bucs W...,nfl,0.220,0.780,0.000,-0.4767
3,Beckham Jr with the rare butt punch,nfl,0.000,1.000,0.000,0.0000
4,Tom Brady looking at AB during his antics today,nfl,0.000,1.000,0.000,0.0000
...,...,...,...,...,...,...
7491,2023 Reverse Retro Concept Series - Boston Bruins,hockey,0.000,1.000,0.000,0.0000
7492,Fun Fact about Boston Fans,hockey,0.000,0.548,0.452,0.5106
7493,Tricky Ricky Rakell does it himself and scores...,hockey,0.167,0.833,0.000,-0.1531
7494,[BUF 3 - NYI 1] Tage Thompson hammers the one ...,hockey,0.000,1.000,0.000,0.0000
7495,[PIT v DET] Matheson to Rakell who goes 5 hole...,hockey,0.000,1.000,0.000,0.0000

In [10]:
table = df2.groupby('subreddit').mean().round(3)
table.to_csv('./outputs/sia_table.csv')

In [11]:
table

             neg    neu    pos  compound
subreddit
baseball   0.052  0.868  0.078     0.055
hockey     0.037  0.882  0.081     0.094
nba        0.051  0.854  0.094     0.096
nfl        0.048  0.883  0.069     0.057
soccer     0.045  0.866  0.088     0.103